project:
  type: book
  output-dir: _book

book:
  title: "Trial Specifications Document"
  subtitle: "Indian Ocean Albacore MSE"
  author:
    - name: Adrian Hordyk
      affiliation: Blue Matter Science
      email: adrian@bluematterscience.com
  date: today
  date-format: "D MMMM YYYY"
  site-url: https://iotcalb.bluematterscience.com/tsd/
  repo-url: https://github.com/Blue-Matter/iotcALB
  navbar:
    left:
      - text: "Albacore MSE Homepage"
        href: https://iotcalb.bluematterscience.com/
      - text: "iotcALB R Package"
        href: https://iotcalb.bluematterscience.com/pkg/
  chapters:
    - index.qmd
    - operating-models.qmd
    - forward-projections.qmd
    - performance-metrics.qmd
    - management-procedures.qmd
    - results.qmd
    - references.qmd

bibliography:
  - references.bib
  - references-extra.bib
csl: apa.csl
link-citations: true

brand: _blue-matter.yml

format:
  html:
    theme:
    - cosmo
    code-link: true
    toc-depth: 3
    toc-expand: true
    lightbox: true
