project:
  type: book
  output-dir: _book

book:
  title: "Trial Specifications Document"
  subtitle: "Indian Ocean Albacore MSE"
  site-url: https://iotcalb.bluematterscience.com/tsd/
  repo-url: https://github.com/Blue-Matter/iotcALB
  chapters:
    - index.qmd
    - operating-model-overview.qmd
    - operating-model-base-case.qmd
    - operating-model-robustness.qmd   
    - fishery-data.qmd
    - forward-projections.qmd
    - management-procedures.qmd
    - performance-metrics.qmd
    - presentation-results.qmd

bibliography: references.bib
csl: apa.csl
link-citations: true

format:
  html:
    theme: cosmo
